fix: fetch emojis from release instead of compiling manually

diff --git a/emoji_gen b/emoji_gen
--- a/emoji_gen
+++ b/emoji_gen
@@ -14,40 +14,19 @@ error() {
   printf "%b\n" "${red}$1${fg_reset}" 1>&2
 }
 
-if ! command -v bundler > /dev/null || ! command -v jq; then
-  if  ! command -v bundler && ! command -v jq; then
-    error "bundler and jq not found"
-  elif  ! command -v bundler; then
-    error "bundler not found"
-  elif ! command -v jq; then
-    error "jq not found"
-  fi
-  exit
+if ! command -v wget > /dev/null; then
+    error "wget not found"
+    exit 1
 fi
 
 
 tmp_dir=$(mktemp -d)
 emoji_dir="$HOME"/.local/share/unicode
+version=2.7
 
-git clone --filter=blob:none https://github.com/Mange/emoji-data "$tmp_dir"
-
-cd "$tmp_dir" || exit
-
-# determine whether to use doas or sudo
-if command -v doas; then
-  make setup || doas bundle install
-
-elif command -v sudo; then
-  make setup || sudo bundle install
-else
-  error "Neither doas or sudo were found. Please install either of them to proceed."
-  exit
-fi
-
-
-make all
-
-# exit if build was not successfull
+wget https://github.com/Mange/emoji-data/releases/download/v${version}/prebuilt-data-v${version}.tar.bz2 -P "$tmp_dir" || exit
+cd "$tmp_dir"
+tar -xf prebuilt-data-v${version}.tar.bz2
 cd data || exit
 
 
